import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import Navbar from "@/components/Navbar";
import StoreProvider from "./StoreProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const checkSession = await checkAndRemoveUserData();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <StoreProvider>
            <div className="sticky top-0 z-40 ">
              <Navbar />
            </div>
            {children}
            <ToastContainer />
          </StoreProvider>
        </Providers>
      </body>
    </html>
  );
}
